version: '3'
services:
  chrome:
    image: browserless/chrome:latest
    ports:
      - "3000:3000"
    volumes:
      - ./appdata:/var/opt
  app:
    platform: ${DOCKER_PLATFORM:-linux/x86_64}
    container_name: 'go-htmltoimg'
    build:
      context: .
    command: /bin/sh
    volumes:
      - .:/var/app
    tty: true
    stdin_open: true
